CREATE TABLE AD_TBL (
    AD_ID    VARCHAR2(15)    PRIMARY KEY,
    AD_PW    CHAR(60)    NOT NULL,
    AD_VISIT_DATE    DATE
);

INSERT INTO AD_TBL VALUES('admin', '$2a$10$dQFCMr0udCI865eG6SoIcOaNr3Y/dgBX.R4qf6rX5KA3jciSnnNjG',sysdate);