CREATE TABLE BOARD (
    BNO NUMBER,
    TITLE   VARCHAR2(100)   NOT NULL,  -- 제목
    CONTENT VARCHAR2(1000)  NOT NULL,  -- 내용
    WRITER  VARCHAR2(100)   NOT NULL,  -- 작성자
    REGDATE DATE    DEFAULT SYSDATE,   -- 등록일
    UPDATEDDATE DATE DEFAULT SYSDATE,
    VIEWCOUNT NUMBER DEFAULT 0,
    CONSTRAINT PK_BOARD PRIMARY KEY(BNO)
 );
 
 CREATE SEQUENCE SEQ_BOARD;