CREATE TABLE ORDETAIL_TBL(
        ORD_CODE        NUMBER      NOT NULL REFERENCES ORDER_TBL(ORD_CODE) ON DELETE CASCADE,
        ITEM_NUM         NUMBER      NOT NULL REFERENCES ITEM_TBL(ITEM_NUM) ON DELETE CASCADE,
        DT_AMOUNT       NUMBER      NOT NULL,
        DT_PRICE        NUMBER      NOT NULL,  -- 역정규화
        PRIMARY KEY (ORD_CODE ,ITEM_NUM)
);