CREATE TABLE REVIEW_TBL(
        REW_NUM         NUMBER,
        DARK_ID         VARCHAR2(15)                NOT NULL,
        ITEM_NUM         NUMBER                      NOT NULL,
        REW_CONTENT     VARCHAR2(200)               NOT NULL,
        REW_SCORE       NUMBER                      NOT NULL,
        REW_REGDATE     DATE DEFAULT SYSDATE        NOT NULL,
        FOREIGN KEY(DARK_ID) REFERENCES DARK_TBL(DARK_ID) ON DELETE CASCADE,
        FOREIGN KEY(ITEM_NUM) REFERENCES ITEM_TBL(ITEM_NUM)ON DELETE CASCADE
);

ALTER TABLE REVIEW_TBL
ADD CONSTRAINT PK_REVIEW_TBL PRIMARY KEY(REW_NUM);

create sequence seq_REVIEW_TBL;
